# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jenkins-neo-theme
email: aarjithn@gmail.com
description: Beautify your Jenkins with the Material Neo theme!
baseurl: ""
url: "http://aarjith.github.io"
twitter_username: aarjithn
github_username:  aarjithn
github_url: "https://github.com/aarjithn/jenkins-neo-theme"

# Build settings
markdown: kramdown
